apiVersion: v1
kind: Service
metadata:
  name: financial-news-api-service
spec:
  selector:
    app: financial-news-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
